### ISSUE TITLE
API + strona działająca lokalnie

### ISSUE THREAD

**Issue by Wertok07** [jacekkow/mpk-ttss#14]
Gdzie znajdę API udostepnione przez ZIKIT?
Co jest przyczyną braku połączenia jeżeli strona jest postawiona na komputerze z dostępem do internetu?

**Comment by jacekkow** [comment]
Proszę spojrzeć na pierwszą linię pliku map.js: https://github.com/jacekkow/mpk-ttss/blob/master/map.js#L1

Jest tam zarówno adres do API, jak i do lokalnego "proxy" w PHP.

Powód, dla którego to proxy jest wymagane, to zaimplementowany w przeglądarkach mechanizm bezpieczeństwa o nazwie same-origin policy. Więcej informacji na ten temat można znaleźć pod adresami:
https://en.wikipedia.org/wiki/Same-origin_policy
https://developer.mozilla.org/en-US/docs/Web/Security/Same-origin_policy
https://sekurak.pl/bezpieczenstwo-html5-podstawy-czesc-2/ (po polsku)

Są dwa (stosunkowo) proste rozwiązania:
- wyłączenie tego mechanizmu w przeglądarce (Chrome można uruchomić z opcją `--disable-web-security` - nie radzę zostawiać tego ustawienia na stałe!) i ustawienie `ttss_base` na wartość zakomentowaną,
- wystawienie strony na lokalnym serwerze z PHP (np. wbudowanym w interpreter: http://php.net/manual/pl/features.commandline.webserver.php).
