### ISSUE TITLE
Pytanie dot. API TTSS

### ISSUE THREAD

**Issue by spitfire** [jacekkow/mpk-ttss#16]
Wiem, że otwarcie ticketa tutaj nie jest dobrą praktyką (problem nie dotyczy aplikacji), ale mam pytanie co do API TYSS, do którego nie mogę znaleźć dokumentacji.
Próbuję za pomocą [Apple Shortcuts](https://support.apple.com/en-us/HT208309) napisać skrót który pokazywałby ilość minut do odjazdu tramwaju przejeżdżającego przez inny przystanek (np. Trasa praca->dom), ale nie wiem który endpoint pozwala na określenie w którym kierunku porusza się tramwaj i jakie są jego kolejne przystanki. Jedyne w miarę bliskie informacje jakie znalazłem to /services/routeInfo/routeStops?routeId, gdzie pokazane są przystanki, ale  nie są one podane w kolejności przejazdu. Gdzie można wyciągnąć taką informację?

**Comment by domints** [comment]
Z tego co wiem, API TTSS nie posiada żadnej dokumentacji ;) 

Zapytanie którego szukasz to:
```
POST /internetservice/services/tripInfo/tripPassages HTTP/1.1
Content-type: application/x-www-form-urlencoded; charset=UTF-8

tripId=6351558574044469265&mode=departure&vehicleId=6352185295672181348&cacheBuster=1539187731947
````

**Comment by jacekkow** [comment]
> otwarcie ticketa tutaj nie jest dobrą praktyką (problem nie dotyczy aplikacji)

Spodziewałem się pytań i nie mam nic przeciwko zadawaniu ich tutaj.

> routeStops

Z moich obserwacji wynika, że `routeStops` zwraca wszystkie przystanki, przez które planowo przejeżdża linia - wliczając w to wyjazdy i powroty do zajezdni. Koniec końców ta metoda nie jest zbyt przydatna.

> Zapytanie którego szukasz to: /internetservice/services/tripInfo/tripPassages

Potwierdzam - `tripPassages` to jedyna rozsądna opcja. Zwraca przystanki danego tramwaju od paru przystanków wstecz do końca trasy.

Wymagany jest tylko jeden parametr: `tripId`. Przykład: http://www.ttss.krakow.pl/internetservice/services/tripInfo/tripPassages?tripId=6351558574045116429

`tripId` zwracają m.in. metody `/internetservice/services/passageInfo/stopPassages/stop` (odjazdy z przystanku), `/internetservice/services/passageInfo/stopPassages/stopPoint` (odjazdy z konkretnego "peronu") oraz `/internetservice/services/vehicleinfo/vehicles` (pozycje wszystkich pojazdów).
