### ISSUE TITLE
Dodanie linii autobusowych MPK

### ISSUE THREAD

**Issue by niutech** [jacekkow/mpk-ttss#18]
Dane dot. odjazdów i pozycji autobusów MPK w Krakowie są dostępne pod ftp://ztp.krakow.pl/ (format GTFS) i http://91.223.13.70/internetservice/ (interaktywnie). Proszę o dodanie ich do https://mpk.jacekk.net.

**Comment by jacekkow** [comment]
Póki co dodane tylko do mapki, niezbyt ładnie.

Następny krok to dodanie do tablic.

Później można pomyśleć o ładniejszej obsłudze całości.

**Comment by p0358** [comment]
Szanuję, również według moich pobieżnych obserwacji autobusy odświeżają się co 5 sekund, podczas gdy tramwaje co 10. Generalnie przy większym refactoringu proponuję do pozycji pojazdów zrobić jakiegoś "workera" na serwerze służącym jako nasze proxy, który przy obecności użytkowników odświeżałby pozycje, dajmy na to, co 2.5 sekundy, następnie przesyłałby zmiany/całość do wszystkich użytkowników websocketem, dzięki temu mielibyśmy aktualizacje w czasie rzeczywistym bez obciążania serwera oryginalnego (a że podczas testów kilka razy padł, to powinno być to dla nas priorytetem). Jak coś, to postarałbym się pomóc, fajnie by było z tego projektu utworzyć dobrą webappkę, którą można by było dodać na telefony do ekranu głównego, i która byłaby dobrą alternatywą dla ślamazarnego i zamkniętoźródłowego Kraków pod ręką

**Comment by niutech** [comment]
Super! Dziękuję bardzo!

**Comment by jacekkow** [comment]
Pozwoliłem sobie wydzielić pomysły @p0358 do osobnych zgłoszeń, a to zamknąć.
