### ISSUE TITLE
Centrowanie mapy na pozycji użytkownika

### ISSUE THREAD

**Issue by nouwak** [jacekkow/mpk-ttss#24]
Na urządzeniach mobilnych bardzo przydatna byłaby możliwość wyśrodkowania mapy na pozycji urządzenia (GPS albo stacje bazowe sieci komórkowej). Mogłoby to być automatyczne centrowanie mapy na przybliżonej lokalizacji podczas inicjalizacji mapy, albo przycisk z boku, pozwalający w każdym momencie na przejście do aktualnej lokalizacji.

**Comment by p0358** [comment]
![image](https://user-images.githubusercontent.com/5182588/52720972-f7ce1480-2fa8-11e9-9e73-5487e9ab4b01.png)
Taki przycisk jak ten? Jeżeli ci się nie pojawia, to może to być przez starą wersję strony trzymaną w cache

**Comment by jacekkow** [comment]
Przepraszam Michał, ale zdążyłem dopisać funkcję zanim Ty zdążyłeś ją zgłosić ;)

**Comment by nouwak** [comment]
Faktycznie, wyczyszczenie pamieci podręcznej pomogło :D 
To się nazywa development, dodawanie funkcji zanim się je zgłosi.
