### ISSUE TITLE
Niepoprawne wyświetlanie trasy linii autobusowych

### ISSUE THREAD

**Issue by kfigiela** [jacekkow/mpk-ttss#25]
Trasy niektórych lini autobusowych nie są wyświetlane poprawnie. Zauważyłem na liniach 175 i 203.

175 – zaznaczyłem poprawną trasę – 175 nie jedzie przez Libertów :)

![image](https://user-images.githubusercontent.com/174118/52853838-0f2e0e80-311d-11e9-9ecc-ce9dfb643fab.png)

203 - poprawna trasa
<img width="1717" alt="zrzut ekranu 2019-02-15 12 30 55" src="https://user-images.githubusercontent.com/174118/52854067-a5623480-311d-11e9-86c9-050dc6c02395.png">

203 - błędna trasa (203 również nie jedzie przez Libertów)
<img width="1717" alt="zrzut ekranu 2019-02-15 12 25 39" src="https://user-images.githubusercontent.com/174118/52854059-a2674400-311d-11e9-9878-0f5c9288fecf.png">

**Comment by domints** [comment]
Niestety trasy przychodzą z systemu TTSS i niestety twórcy aplikacji nie mają wpływu na głupoty wysyłane przez MPK/ZIKiT

**Comment by kfigiela** [comment]
Ok, dzięki!
