### ISSUE TITLE
Missing trams on map

### ISSUE THREAD

**Issue by pasuder** [jacekkow/mpk-ttss#26]
Starting from yesterday, there are missing trams on map.

<img width="457" alt="Zrzut ekranu 2019-03-25 o 08 13 38" src="https://user-images.githubusercontent.com/3436085/54901171-f3fdae00-4ed5-11e9-98d9-0698ae53f9d7.png">

<img width="1661" alt="Zrzut ekranu 2019-03-25 o 08 13 50" src="https://user-images.githubusercontent.com/3436085/54901182-fbbd5280-4ed5-11e9-9d25-264416ba4ed1.png">

Some 503 from server.

**Comment by jacekkow** [comment]
Works at this time, yet I know about the issues. This will be handled in https://github.com/jacekkow/mpk-ttss/issues/22
