### ISSUE TITLE
Brak informacji o pojeździe dla tramwajów

### ISSUE THREAD

**Issue by lukasznidecki** [jacekkow/mpk-ttss#31]
Jak w temacie. Info o autobusach działa.

**Comment by jacekkow** [comment]
Niestety plik na FTP Zarządu Transportu Publicznego (ftp://ztp.krakow.pl/pliki-gtfs/VehiclePositions_T.pb) nie zawiera informacji o żadnym tramwaju - ma 13 bajtów, tj. sam nagłówek.

Jeśli do jutra się nie poprawi, postaram się skontaktować z ZTP.
