### ISSUE TITLE
Busses API is not avaliaveble

### ISSUE THREAD

**Issue by majkrzak** [jacekkow/mpk-ttss#33]
Querying `https://mpk.jacekk.net/proxy_bus.php/services/passageInfo/stopPassages/stop?stop=<stop_id>&mode=departure` results in 503 error.

**Comment by jacekkow** [comment]
Sorry, but I cannot do anything about it. The MPK site I am using (http://ttss.mpk.krakow.pl/internetservice/) is empty, there are no buses nor stops available at that URL right now. What is more official GTFS data files (ftp://ftp.ztp.krakow.pl/pliki-gtfs/) contain no live bus data, too.

This is an issue that MPK and/or ZTP must fix themselves. You can try contacting gtfs@mpk.krakow.pl - results may vary.
