### ISSUE TITLE
Brak przystanków tramwajowych w rejonie Łagiewnik

### ISSUE THREAD

**Issue by hektor0** [jacekkow/mpk-ttss#34]
Brak następujących przystanków tramwajowych w wyszukiwarce:

1. Turowicza
2. Sanktuarium Bożego Miłosierdzia (nazwa się wyświetla, ale nie ma żadnych odjazdów).

Wymienione przystanki są dostępne z poziomu mapy, ale nie w wyszukiwarce.

**Comment by jacekkow** [comment]
Lista przystanków dla wyszukiwarki bierze się z tego pliku:
https://github.com/jacekkow/mpk-ttss/blob/master/stops/stops.php

Trochę mi zajęło dotarcie do wszystkich zmian od ostatniej aktualizacji:
https://github.com/jacekkow/mpk-ttss/commit/ee953eef09cc090dc98a09038ab97be55875a2a5

Powinno już działać.

**Comment by hektor0** [comment]
Działa OK,

Dziekuję i Pozdrawiam
