### ISSUE TITLE
Zacięcie pozycji pojazdów na mapie

### ISSUE THREAD

**Issue by pmk-gh** [jacekkow/mpk-ttss#35]
Autobus BU997 (jeśli jest w systemie) ma stałą pozycję koło pętli Górka Narodowa, autobus DR548  (jeśli jest w systemie) ma stałą pozycję na al. Jana Pawła II tuż przed Rondem Czyżyńskim, a tramwaj RY839 (jeśli jest w systemie) ma stałą pozycję na al. Pokoju między przystankami Rondo 308. Dywizjonu i Centralna. Po kliknięciu w nie wyświetlają się prawdziwe trasy i przystanki w czasie rzeczywistym. Dodatkowo, np. na stronie krakowpodreka.pl ich pozycje na mapie są prawidłowe. Coś się pewnie przycięło i została zapisana pozycja z tego momentu.

**Comment by domints** [comment]
Ta teza jest dla mnie wątpliwa z jednego całkiem ważnego powodu - API Jacka nie robi żadnego cache, modyfikacji danych, przypisuje tylko nr taborowy i przekazuje wszystko co idzie z systemów TTSS.
Dokładnie to samo jest w ttss.mpk.krakow.pl:
<img width="1025" alt="obraz" src="https://github.com/jacekkow/mpk-ttss/assets/1096161/0ec16280-1fe9-431e-bfa8-ba6cfedb07ca">

Co więcej, na stronie krakowpodreka.pl ten sam pojazd (tutaj DR548) jest w tym samym miejscu, mimo tego, że rozkładówka mówi że jest przy Młynówce:
<img width="1061" alt="obraz" src="https://github.com/jacekkow/mpk-ttss/assets/1096161/ac45fac3-27d6-488d-831f-f8143d55eea6">

Issue do zamknięcia, błąd jest w źródle danych (TTSS), żadna aplikacja z tym nie może nic zrobić o ile nie zaczniemy się bawić w sztuczne generowanie pozycji na bazie rozkładówki.

**Comment by jacekkow** [comment]
Nic się nie przycięło, prócz GPS-u w pojeździe.

W systemie TTSS są dwie różne pozycje:
- skorygowana (pochodząca z GPS-u oraz interpolowana z odległości między przystankami, dodatkowo przyciągnięta do torów, czasami niepoprawnie),
- faktyczna (tylko z odbiornika GPS pojazdu).

Pierwsza jest pod adresem: http://www.ttss.krakow.pl/internetservice/geoserviceDispatcher/services/vehicleinfo/vehicles
Druga pojawia się po dodaniu: `?positionType=RAW` do adresu (choć co do samej wartości nie jestem pewny - na pewno z RAW działa).

Moja strona używa tej drugiej - ona jest też w plikach GTFS (używanych przez dla Google, Jakdojade czy https://beta.ttss.pl/).

Ma ona też swoje zalety - widać niektóre tramwaje nie będące w trasie.

**Comment by jacekkow** [comment]
PS. W/w dotyczy tramwajów - jak zauważył @domints w autobusach problem i tak występuje.
