### ISSUE TITLE
TTSS nie dziala dla tramwajow 

### ISSUE THREAD

**Issue by galandilias** [jacekkow/mpk-ttss#37]
![obraz](https://github.com/user-attachments/assets/94232628-9e12-4638-a891-48c5a9928080)

Zgodnie z powyzszym prace jeszcze potrwaja - mozliwe ze nawet pol roku ;) stad moze warto przesiasc sie tymczasowo na wersje beta? Uzywam serwisu w Home Assistant - niestety teraz pobieranie danych o tramwajach nie dziala.

**Comment by jacekkow** [comment]
Mogę wrzucić "belkę" na głównej stronie z sugestią skorzystania z bety.

**Comment by galandilias** [comment]
A API? :) Bo ja biore stad :) takze przydalo by mi sie jakby zapytania szly do wersji beta :)

**Comment by domints** [comment]
A tak swoją drogą, o jakiej becie mówisz? Jest jakieś beta API od ZTP?

W dniu czw., 1.08.2024 o 15:17 galandilias ***@***.***>
napisał(a):

**Comment by galandilias** [comment]
Ok - to ja jeszcze moze wyprostuje o co mi dokladnie chodzi ;) i moze szanowne grono mi poradzi ;)

Mam e-ink ekrany w mieszkaniu pokazujace odjazdy tramwajow z pobliskiego przystanku (ESPHome + Home Assistant). Do poczatku lipca ladnie dzialaly, niestety teraz API ktorego uzywalem juz nie jest dostepne:
`http://www.ttss.krakow.pl/internetservice/services/passageInfo/stopPassages/stop?stop={"NUMER_PRZYSTANKU"}&mode={"departure"}&language=pl`
Czy ktorys z Was ma wiedze czy da sie jakos dane o odjazdach z przystankow ciagle pobierac? Dla autobusow juz/jeszcze dziala tylko to jest inne API:
`http://ttss.mpk.krakow.pl/internetservice/services/passageInfo/stopPassages/stop?stop={"NUMER_PRZYSTANKU"}&mode={"departure"}`

**Comment by domints** [comment]
> Mówię o https://ttss.pl/map.html vs https://beta.ttss.pl/map.html (beta).
> 
> To drugie od dawna ciągnie dane tylko z GTFS.

Aaaa, bo plik VehiclePositions_T działa, jak doszedłem do tego, że api TTSS zdechło i sprawdzałem to był pusty, może akurat trafiłem na zły moment :)

No cóż, trzeba dopisać nowy fallback do mojego API :)

**Comment by SokZKomucha** [comment]
Dzień dobry, dołączam się do dyskusji. 
_Prawdopodobnie_ TTSS już funkcjonuje tak, jak powinien. Co jakiś czas sobie wchodziłem na stronę i patrzyłem, czy działa; w chwili pisania tego, poniższe zapytanie poprawnie (?) zwraca listę odjazdów tramwajów z przystanku, w tym przypadku, Rondo Mogilskie:
`https://www.ttss.krakow.pl/internetservice/services/passageInfo/stopPassages/stop?stop=125&mode=departure&language=pl`

**Comment by jacekkow** [comment]
URL poprawiony.

Niestety nie działa takie zapytanie do API (zwraca 404):
https://ttss.krakow.pl/internetservice/geoserviceDispatcher/services/stopinfo/stopPoints

**Comment by domints** [comment]
Dane te co `stopPoints` (przynajmniej to co widzę dla autobusów) można wyciągnąć z plików GTFS, z stops.txt

**Comment by SokZKomucha** [comment]
Warto też wspomnieć, że endpoint ze ścieżkami pojazdów (`/internetservice/geoserviceDispatcher/services/pathinfo/route?id={id_pojazdu}`) też odmawia posłuszeństwa - zwraca 404/500

**Comment by domints** [comment]
Ścieżki w Krakowskim GTFSie też są o ile dobrze pamietam ;) trzeba by
jakiegoś API, które by to serwowało, nie? ;)

W dniu sob., 7.09.2024 o 14:34 CCl₂F₂ ***@***.***> napisał(a):
