### ISSUE TITLE
Oznaczenie przodu pojazdu

### ISSUE THREAD

**Issue by Futrzasty** [jacekkow/mpk-ttss#7]
Na mapie nie jest oznaczone, który narożnik trójkąta to przód tramwaju i na przykład na węzłach, czy skrzyżowaniach nie widać w którą stronę jedzie. Można by oznaczyć kolorem przedni wierzchołek, lub tylny bok trójkącika (robiąc z ikony swego rodzaju strzałkę).

**Comment by domints** [comment]
+1
Strzałka mogłaby być wydłużona. Co Ty na to @jacekkow?

**Comment by jacekkow** [comment]
Aktualnie trójkącik to RegularShape z biblioteki OpenLayers (http://openlayers.org/en/latest/apidoc/ol.style.RegularShape.html). Zmiana kształtu będzie wymagała przejścia na np. ol.style.Icon (http://openlayers.org/en/latest/apidoc/ol.style.Icon.html). Da się zrobić.

**Comment by jacekkow** [comment]
Trójkąt jest teraz zrobiony w SVG.

Jeśli nie widać zmian, to trzeba przeładować stronę (Ctrl+F5).
